---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onestop-manager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "onestop-manager.name" . }}
    helm.sh/chart: {{ include "onestop-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "onestop-manager.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "onestop-manager.name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- with .Values.config }}
        checksum/config: {{ . | sha256sum }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.debug }}
      shareProcessNamespace: true
      {{- end }}
      containers:
      {{- if .Values.debug }}
      - name: debug
        image: centos
        command: ["tail", "-f", "/dev/null"]
      {{- end }}
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.debug }}
        - name: jdwp
          containerPort: 5005
        {{- end }}
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ include "onestop-manager.kafka.bootstrap.servers" . }}"
        - name: KAFKA_SCHEMA_REGISTRY_URL
          value: "{{ include "onestop-manager.kafka.schema.registry.url" . }}"
        {{- if .Values.config }}
        - name: spring.config.additional-location
          value: /etc/conf/application.yaml
        {{- end }}
        {{- if .Values.debug }}
        - name: JAVA_TOOL_OPTIONS
          value: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'
        {{- end }}
        volumeMounts:
        {{- if .Values.config }}
        - name: config
          mountPath: /etc/conf
        {{- end }}
        {{/* TODO: liveness, readiness */}}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- if .Values.config }}
      volumes:
      - name: config
        configMap:
          name: {{ include "onestop-manager.fullname" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
