---
# Example of config that can be applied when the "cas" spring profile is active
######

# -- allows for better security logs for debugging --
#logging.level.org.pac4j.springframework.web: DEBUG
#logging.level.org.pac4j.core.engine: DEBUG
#logging.level.org.pac4j.cas: DEBUG

# -- The prefix URL of the CAS server --
# -- note: will require actually registering service in the future...
#login-gov:
#  client-id: "urn:gov:gsa:openidconnect.profiles:sp:sso:noaa:onestop_user_8080"
#  scopes: "openid email"
#  use-nonce: true
#  acr-values: "http://idmanagement.gov/ns/assurance/loa/1"

# Configure the list of CAS users which have the ROLE_ADMIN
# and therefore can access admin endpoints
#authorization:
#  roles:
#    ROLE_ADMIN:
#      - user.one
#      - user.two


logingov:
  client-id: "urn:gov:gsa:openidconnect.profiles:sp:sso:noaa:onestop_user_8080"
  discovery-uri: "https://idp.int.identitysandbox.gov/.well-known/openid-configuration"
  scopes: "openid email"
  use-nonce: true
  acr-values: "http://idmanagement.gov/ns/assurance/loa/1"

authorization:
  roles:
    ROLE_PUBLIC:
      - elliott.richerson@noaa.gov