image: ncei/centos7-openjdk11:build

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "1346-gitlab-ci"' # TODO - remove after merged

stages:
  - build
  - test
  - security
  - deploy

variables:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false,org.gradle.caching=true,org.gradle.parallel=true"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  tags:
    - build
  script:
    - ./gradlew --stacktrace assemble
  artifacts:
    paths:
      - ".gradle"
      - "*/.gradle"
      - "build"
      - "*/build"
      - "*/node_modules"

#owasp_update:
#  stage: build
#  tags:
#    - build
#  script:
#    - ./gradlew --stacktrace dependencyCheckUpdate
#  artifacts:
#    paths:
#      - ".gradle/dependency-check-data"

gradle_check:
  stage: test
  tags:
    - build
  script:
    - ./gradlew --stacktrace check -x BuildDockerImage -x indexer:integrationTest -x search:integrationTest
  artifacts:
    paths:
      - "*/build/reports/*"

owasp_dependency_check:
  stage: security
  tags:
    - build
  script:
    - ./gradlew --stacktrace dependencyCheckUpdate dependencyCheckAggregate
  artifacts:
    paths:
      - "build/reports/*.html"

sonarqube:
  stage: security
  tags:
    - security
  script:
    - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.ncei.noaa.gov -Dsonar.login=${SONAR_TOKEN}

#gitlab_package:
#  stage: deploy
#  tags:
#    - container
#  script:
#    - ./gradlew publish
#  only:
#    - master
