image: ncei/centos7-openjdk11:build

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "1346-gitlab-ci"' # TODO - remove after merged

stages:
  - build
  - test
  - security
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false,org.gradle.caching=true,org.gradle.parallel=true"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  tags:
    - build
  script:
    - gradle assemble
  artifacts:
    paths:
      - ".gradle"
      - "build"
      - "*/build"
      - "*/.gradle"
      - "*/node_modules"

gradle_check:
  stage: test
  tags:
    - container
  script:
    - gradle check -x BuildDockerImage -x indexer:integrationTest -x search:integrationTest
  artifacts:
    paths:
      - "*/build/reports/*"

dependency_check:
  stage: security
  tags:
    - security
  script:
    - gradle dependencyCheckAggregate
  artifacts:
    paths:
      - "build/reports/*.html"

#sonarqube:
#  stage: security
#  tags:
#    - security
#  script:
#    - gradle sonarqube -Dsonar.host.url=https://sonarqube.ncei.noaa.gov -Dsonar.login=${SONAR_TOKEN}

#gitlab_package:
#  stage: deploy
#  tags:
#    - container
#  script:
#    - gradle publish
#  only:
#    - master
