---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onestop-registry.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "onestop-registry.name" . }}
    helm.sh/chart: {{ include "onestop-registry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "onestop-registry.name" . }}
    release: {{ .Release.Name }}
