apiVersion: v1
entries:
  onestop:
  - apiVersion: v1
    created: "2020-03-10T17:47:12.981243-06:00"
    description: A Helm chart for the OneStop system
    digest: b8a0cc3bcae73fdc6207904e1756da29cf0b79b9f1eb14de52e9a3ba14530dcb
    name: onestop
    urls:
    - onestop-1.0.0-alpha.tgz
    version: 1.0.0-alpha
  - apiVersion: v1
    appVersion: 2.4.0
    created: "2020-03-10T17:47:12.978752-06:00"
    description: A Helm chart for the OneStop system
    digest: aa04366b561b977aaa8a8f1712c5711bafe4bc8512793bafdcf9b83dcc8f9e2c
    name: onestop
    urls:
    - onestop-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: 2.4.0
    created: "2020-03-10T17:47:12.969149-06:00"
    description: A Helm chart for the OneStop system
    digest: 59a0b6cbdbb1f58f70061fac2a45fc58045fce3fd32f6d9b24aa4e37e4403edf
    name: onestop
    urls:
    - onestop-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-03-10T17:47:12.963023-06:00"
    description: A Helm chart for the OneStop system
    digest: a38e89b18d2fdb850b206cceb3525fb36a0ed6ef78a10765eda3b0b2cc3f7895
    name: onestop
    urls:
    - onestop-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-03-10T17:47:12.960843-06:00"
    description: A Helm chart for the OneStop system
    digest: 965fd23b5088778b98daec5564c03db77261bf8b1f7077bef8b53ddd0bbb76b8
    name: onestop
    urls:
    - onestop-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-03-10T17:47:12.959375-06:00"
    description: A Helm chart for the OneStop system
    digest: 0b792e2abf7c8c66bbf4f663cbda50d85b6fa23ca8bd2acdfa34d87f3a61317f
    name: onestop
    urls:
    - onestop-0.1.0.tgz
    version: 0.1.0
generated: "2020-03-10T17:47:12.957832-06:00"
